project_name: study_xxqg
env:
  - GO111MODULE=on
builds:
  - binary: study_xxqg
    ldflags: -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    archive:
      format: zip
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      strip_components: 0
  - binary: study_xxqg
    ldflags: -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    image_templates:
      - name: xlh001/study_xxqg
        dockerfile: Dockerfile
        registry: hub.docker.com
        username:
          from_secret: ${{ secrets.DOCKERHUB_USERNAME }}
        password:
          from_secret: ${{ secrets.DOCKERHUB_TOKEN }}
        tags:
          - latest
          - "{{.Version}}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    include:
      - feat
      - fix
archives:
  - id: binary
    builds:
      - linux
      - windows
      - darwin
    format_defaults:
      format: tar.gz
  - id: linux
    builds:
      - linux
    format_defaults:
      format: tar.gz
nfpms:
  - license: MIT
    homepage: https://github.com/xlh001/study_xxqg
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.{{ .Format }}"
    maintainer: xlh001
    builds:
      - linux
    formats:
      - rpm
      - deb
test:
  image: golang:1.18
  commands:
    - go test -v ./...
release:
  github:
    owner: xlh001
    repository: study_xxqg
  draft: false
  prerelease: false
  files:
    - "study_xxqg_*"
  body: "Release {{.Version}}"
