project_name: study_xxqg

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

steps:
  - name: lint
    image: golangci/golangci-lint:v1.42.1-alpine
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.17-alpine
    commands:
      - go test -race ./...

  - name: build
    image: golang:1.17-alpine
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    commands:
      - go build -trimpath -ldflags="-w -s -X main.Version={{.Version}}" -o study_xxqg

  - name: publish
    image: plugins/docker
    settings:
      registry: docker.io
      repo: xlh001/study_xxqg
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
        - "{{ .Tag }}"
        - "{{ .Tag }}-{{ .Env.FOOBAR }}"
        - "v{{ .Major }}"
      build_args:
        - CGO_ENABLED=0
        - GO111MODULE=on
      cache_from:
        - xlh001/study_xxqg:latest
      cache_to:
        - xlh001/study_xxqg:latest
      platforms:
        - linux/amd64
        - linux/arm64

  - name: nfpm
    image: goreleaser/nfpm:v2
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    commands:
      - nfpm pkg --config nfpm.yaml

builds:
  - id: build
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -w -s -X main.Version={{.Version}}

dockers:
  image_templates:
    - "xlh001/study_xxqg:latest"
    - "xlh001/study_xxqg:{{ .Tag }}"
    - "xlh001/study_xxqg:{{ .Tag }}-{{ .Env.FOOBAR }}"
    - "xlh001/study_xxqg:v{{ .Major }}"
  use: buildx
  dockerfile: Dockerfile

docker_manifests:
  - name_template: "xlh001/study_xxqg:{{ .Version }}"
    image_templates:
      - "xlh001/study_xxqg:latest"
      - "xlh001/study_xxqg:{{ .Tag }}"
      - "xlh001/study_xxqg:{{ .Tag }}-{{ .Env.FOOBAR }}"
      - "xlh001/study_xxqg:v{{ .Major }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: binary
    builds:
      - build
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: MIT
    homepage: https://github.com/xlh001/study_xxqg
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: xlh001
    builds:
      - build

hooks:
  - id: slack
    channel: "#releases"
    body_template: |
      {{ .ProjectName }} {{ .Version }} has been released! :tada:
    when:
      condition: success

signs:
  - cmd: gpg --batch --yes --armor --detach-sign --output "{{ .ArtifactName }}.asc" "{{ .ArtifactPath }}"
