# .goreleaser.yml

project_name: study_xxqg

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.VERSION=v{{.Version}}
    docker:
      - image: xlh001/study_xxqg
        build_context: .
        tags:
          - latest
          - v{{.Version}}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: binary
    builds:
      - build
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: AGPL 3.0
    homepage: https://github.com/xlh001/study_xxqg
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: johlanse
    builds:
      - build
