name: CI
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

<<<<<<< HEAD
permissions:
  contents: write
=======
on: [push, pull_request]

env:
  BINARY_PREFIX: "study_xxqg_"
  BINARY_SUFFIX: ""
  COMMIT_ID: "${{ github.sha }}"
  PR_PROMPT: "::warning:: Build artifact will not be uploaded due to the workflow is trigged by pull request."
  LD_FLAGS: "-w -s"
>>>>>>> afacf917d61c4a518827f9c9a81c25ceaad7d10f

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
<<<<<<< HEAD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

=======
      - name: Fetch all tags
        run: git fetch --force --tags
>>>>>>> afacf917d61c4a518827f9c9a81c25ceaad7d10f
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

<<<<<<< HEAD
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
      - name: Build binary file
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          IS_PR: ${{ !!github.head_ref }}
          CGO_ENABLED: 0
        run: |
          if [ $GOOS = "windows" ]; then export BINARY_SUFFIX="$BINARY_SUFFIX.exe"; fi
          if $IS_PR ; then echo $PR_PROMPT; fi
          export BINARY_NAME="$BINARY_PREFIX$GOOS_$GOARCH$BINARY_SUFFIX"
          export LD_FLAGS="-w -s -X main.VERSION=unknown"
          go mod tidy
          go build -o "output/$BINARY_NAME" -trimpath -ldflags "$LD_FLAGS" ./
          echo ::${{ !!github.head_ref }}
          echo ::${{ !github.head_ref }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: output/
>>>>>>> afacf917d61c4a518827f9c9a81c25ceaad7d10f
